deploymentType: "StatefulSet"
replicaCount: 1
edition: "community"
image:
  repository: sonarqube
  tag: 9.8.0-{{ .Values.edition }}
  pullPolicy: IfNotPresent
securityContext:
  fsGroup: 1000
containerSecurityContext:
  runAsUser: 1000
elasticsearch:
  configureNode: true
  bootstrapChecks: true
service:
  type: LoadBalancer #Change to ClusterIP to have it be private only
  externalPort: 9000
  internalPort: 9000
  labels:
  annotations: {}
affinity: {}
tolerations: []
nodeSelector: {}
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /
startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 24
  sonarWebContext: /
caCerts:
  enabled: false
  image: adoptopenjdk/openjdk11:alpine
  secret: your-secret
initSysctl:
  enabled: true
  vmMaxMapCount: 524288
  fsFileMax: 131072
  nofile: 131072
  nproc: 8192
  securityContext:
    privileged: true
initFs:
  enabled: true
  securityContext:
    privileged: true
prometheusExporter:
  enabled: true
  version: "0.16.0"
  noCheckCertificate: false
  webBeanPort: 8000
  ceBeanPort: 8001
  config:
    rules:
      - pattern: ".*"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
annotations: {}
resources:
  limits:
    cpu: 800m
    memory: 4Gi
  requests:
    cpu: 400m
    memory: 2Gi
postgresql:
  enabled: true
  service:
    port: 5432
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 200Mi
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 20Gi
    storageClass:
  securityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: 0
podLabels: {}
sonarqubeFolder: /opt/sonarqube
tests:
  image: bitnami/minideb-extras
  enabled: true
  resources: {}
  initContainers:
    image: bats/bats:1.2.1
    resources: {}
terminationGracePeriodSeconds: 60